### PR TITLE
Account for spent xp for prestige level

### PR DESCRIPTION
**Pull request by Southpaw018**

### CODE REVIEW

**Comment by TotomInc** [comment]
Thanks, I manually fixed this issue!

**Comment by Southpaw018** [comment]
If you did use this for your idea and just pasted it in manually, I would have appreciated you merging it instead to give me credit.

That said, I'm still glad I could help. Feel free to post new issues and ping me if you'd like any further assistance with the code!

**Comment by TotomInc** [comment]
Really sorry, next time I will use pull requests!

Thanks for fixing this bug!

**Comment by Southpaw018** [comment]
No problem, man. Let me know if there's anything else I can do to help.

**Pull request closed without merging**
